version: '3.8'

x-base: &base
  build:
    dockerfile: develop.Dockerfile
  entrypoint: echo 'ok!'
  tty: true
  stdin_open: true
  volumes:
    - ./:/app
  working_dir: /app
  environment:
    NODE_ENV: development
    AMQP_URL: amqp://guest:guest@rabbitmq:5673
    BASE_URL: http://web:9876
    REDIS_URL: redis://redis:6380
    STORAGE_ENDPOINT: http://minio:9100
  depends_on:
    - redis
    - rabbitmq

x-minio: &minio
  image: quay.io/minio/minio:latest
  command: server --console-address ":9101" --address ":9100" /data
  env_file: .env
  environment:
    MINIO_SERVER_URL: http://localhost:9100
    MINIO_BROWSER_REDIRECT_URL: http://localhost:9101
  expose:
    - 9100:9100
    - 9101:9101
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9100/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  web:
    <<: *base
    entrypoint: yarn web-dev
    restart: on-failure
    ports:
      - 9876:9876

  worker:
    <<: *base
    entrypoint: sh -c 'wait-for redis:6380 rabbitmq:5673 -- yarn worker-dev'
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 5673:5673
      - 15673:15673
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    ports:
      - 6380:6380
    restart: on-failure

  minio:
    <<: *minio
    ports:
      - 9100:9100
      - 9101:9101
    volumes:
      - storage1:/data

  minio-mc:
    image: quay.io/minio/mc:latest
    env_file: .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local $STORAGE_ENDPOINT $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb local/$STORAGE_BUCKET_NAME;
      "

volumes:
  rabbitmq:
  redis:
  storage1:
